config/routes.rb
Friends::Application.routes.draw do
  resources :locations
  resources :change_locations
  root :to => 'locations#index'
end

app/models/calculation_coordinate.rb
class CalculationCoordinate
  def initialize(latA, latB, logA, logB)
    @latA = latA
    @latB = latB
    @logA = logA
    @logB = logB
  end
  
  def calculate
    latitude  = sum_coordinate(@latA, @latB) if positive(@latA, @latB)
    longitude = sum_coordinate(@logA, @logB) if positive(@logA, @logB)
    
    latitude  = subtract_coordinate(@latA, @latB) if negative(@latA, @latB)
    longitude = subtract_coordinate(@logA, @logB) if negative(@logA, @logB)
    
    (latitude + longitude).abs
  end
  
  def sum_coordinate(coordinateA, coordinateB)
    coordinateA.abs + coordinateB.abs
  end
  
  def subtract_coordinate(coordinateA, coordinateB)
    coordinateA.abs - coordinateB.abs
  end
  
  def negative(coordinateA, coordinateB)
    coordinateA > 0 && coordinateB > 0 || 
    coordinateA < 0 && coordinateB < 0
  end
  
  def positive(coordinateA, coordinateB)
    coordinateA > 0 && coordinateB < 0 || 
    coordinateA < 0 && coordinateB > 0
  end
end

app/models/geo.rb
class Geo
  def initialize(my_location, locations=[])
    @my_location = my_location
    @locations = locations
    @range = []
  end
  
  def find_close_by_coordinates
    @locations.map do |location|
      @range << { :location_id => location.id, :distance => calculate(location) }
    end
    @range.sort_by { |k| k[:distance]}
  end
  
  private
  def calculate(location)
    CalculationCoordinate.new(
      @my_location.latitude, location.latitude, 
      @my_location.longitude, location.longitude).calculate
  end
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :latitude, :longitude, :my_location, :address
  
  scope :where_ami, where(:my_location => 'Here')
  scope :visited, where(:my_location => 'visited')
  scope :not_visited, where(:my_location => nil)
  
  def self.closet_to_me
    my_location = where_ami.first
    Geo.new(my_location, not_visited).find_close_by_coordinates
  end
  
  def self.three_close_to_me
    closet_to_me.first(3).map {|location| location[:location_id]}
  end
end

app/models/location_generator.rb
class LocationGenerator
  def initialize
  end
  
  def make!
    location_create
  end

  def randon_latitude
    -23.12 + Random.rand(5.1)
  end
  
  def randon_longitude
    -50.12 + Random.rand(7.1)
  end
  
  def location_create
    Location.create(:latitude => randon_latitude, :longitude => randon_longitude)
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html, :json, :js

  protect_from_forgery
end

app/controllers/change_locations_controller.rb
class ChangeLocationsController < ApplicationController
  before_filter :find_locations, :my_location, :only => [:index]
  
  def index
    change_my_location(@locations, @my_location)
    respond_to do |format|
      format.js
    end
  end


  private
  def find_locations
    @locations  = Location.scoped
  end
  
  def my_location
    @my_location = Location.where_ami.first
  end
  
  def change_my_location(locations, my_location)
    if locations.present?
      locations_unvisted = locations.not_visited
      move_to(locations_unvisted.first, my_location)
    end
  end
  
  def move_to(location, my_location)
    location.update_attributes(:my_location => 'Here') if location.present?
    my_location.update_attributes(:my_location => 'visited') if my_location.present?
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_filter :destroy_all, :only => [:index]
  before_filter :automatic_generate_locations, :only => [:index]

  def index    
    @locations = Location.all
    @locations.first.update_attributes(:my_location => 'Here')
    respond_with @locations
  end
  
  private  
  def destroy_all
    Location.destroy_all  
  end
      
  def automatic_generate_locations
    5.times{ LocationGenerator.new().make! }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
  def colorize_by_distance(location)
    if location.my_location == 'Here'
      "where_iam"
    else
      "closer" if has_include_ids?(location)
    end
  end
  
  def has_include_ids?(location)
    close_ids = Location.three_close_to_me
    close_ids.include? location.id and location.my_location != 'visited'
  end  
end

app/views/change_locations/index.js.erb
$(".table").html('<%= escape_javascript render("locations/list", :locations => @locations) %>');

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li><%= link_to "Friends Locations", locations_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Friends</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">Friends</a>
        <div class="nav-collapse">
          <%= render 'layouts/navigation' %>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="span9"><%= yield %></div>
    </div>
  </div>  
</body>
</html>

app/views/locations/_list.html.erb
<thead>
  <tr>
    <th>Friends</th>
    <th>My location</th>
    <th>Address</th>
    <th>Latitude</th>
    <th>Longitude</th>
  </tr>
</thead>
<tbody>
  <% locations.each do |location| %>
    <tr class= <%= colorize_by_distance(location) %> >
      <td><%= location.id %></td>
      <td><%= location.my_location %></td>
      <td><%= location.address %></td>
      <td><%= location.latitude %></td>
      <td><%= location.longitude %></td>
    </tr>
  <% end %>
</tbody>

app/views/locations/index.html.erb
<%- model_class = Location -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>

<div id="list">
  <table class="table">
      <%= render 'list', :locations => @locations %>  
  </table>
</div>